const B='http://localhost:3001';
const stamp=Date.now();
const call=async(m,p,t,body)=>{const r=await fetch(B+p,{method:m,headers:{'content-type':'application/json',...(t?{authorization:'Bearer '+t}:{})},body:body?JSON.stringify(body):undefined});let j=null;try{j=await r.json()}catch{}return{s:r.status,j}};
const reg=async(n)=>{const r=await call('POST','/auth/register',null,{email:`smoke-${n}-${stamp}@sprintio.test`,password:'smoke-pass-1234'});return{t:r.j.accessToken,id:r.j.user.sub}};
const ok=(name,cond,extra='')=>{console.log((cond?'PASS ':'FAIL ')+name+(cond?'':' '+extra));if(!cond)process.exitCode=1};
const A=await reg('a'),Bo=await reg('b'),C=await reg('c');
const board=(await call('POST','/boards',A.t,{title:'Smoke'})).j;
const list=(await call('POST',`/boards/${board.id}/lists`,A.t,{title:'L'})).j;
const card=(await call('POST',`/lists/${list.id}/cards`,A.t,{title:'C'})).j;
ok('card create returns assignees[]',Array.isArray(card.assignees));
ok('stranger cannot read board',(await call('GET',`/boards/${board.id}`,Bo.t)).s===404);
ok('stranger cannot list lists',(await call('GET',`/boards/${board.id}/lists`,Bo.t)).s===404);
ok('stranger cannot create invite',(await call('POST',`/boards/${board.id}/invite`,Bo.t)).s===404);
const inv=(await call('POST',`/boards/${board.id}/invite`,A.t)).j;
ok('owner gets invite token',typeof inv.token==='string'&&inv.token.length===48);
ok('invite is idempotent',(await call('POST',`/boards/${board.id}/invite`,A.t)).j.token===inv.token);
const pv=await call('GET',`/boards/join/${inv.token}`,Bo.t);
ok('preview shows title, not member',pv.s===200&&pv.j.title==='Smoke'&&pv.j.isMember===false);
ok('bad token 404',(await call('GET','/boards/join/nope',Bo.t)).s===404);
ok('join works',(await call('POST',`/boards/join/${inv.token}`,Bo.t)).s===201);
ok('join is idempotent',(await call('POST',`/boards/join/${inv.token}`,Bo.t)).s===201);
const bd=(await call('GET',`/boards/${board.id}`,Bo.t)).j;
ok('member reads board with 2 members',bd.members?.length===2);
ok('member does NOT see invite token',bd.inviteToken===null);
ok('owner sees invite token',(await call('GET',`/boards/${board.id}`,A.t)).j.inviteToken===inv.token);
ok('shared board in member list',(await call('GET','/boards',Bo.t)).j.some(x=>x.id===board.id));
ok('boards list never leaks token',(await call('GET','/boards',A.t)).j.every(x=>!('inviteToken' in x)));
ok('member can add card',(await call('POST',`/lists/${list.id}/cards`,Bo.t,{title:'by member'})).s===201);
ok('member cannot rename board',(await call('PATCH',`/boards/${board.id}`,Bo.t,{title:'x'})).s===404);
ok('member cannot delete board',(await call('DELETE',`/boards/${board.id}`,Bo.t)).s===404);
ok('member cannot mint/revoke invite',(await call('DELETE',`/boards/${board.id}/invite`,Bo.t)).s===404);
ok('member self-assigns',(await call('PUT',`/cards/${card.id}/members/${Bo.id}`,Bo.t)).s===200);
ok('member assigns owner',(await call('PUT',`/cards/${card.id}/members/${A.id}`,Bo.t)).s===200);
ok('assign twice is fine',(await call('PUT',`/cards/${card.id}/members/${Bo.id}`,Bo.t)).s===200);
ok('cannot assign non-member',(await call('PUT',`/cards/${card.id}/members/${C.id}`,A.t)).s===400);
ok('stranger cannot assign',(await call('PUT',`/cards/${card.id}/members/${C.id}`,C.t)).s===404);
const ls=(await call('GET',`/boards/${board.id}/lists`,Bo.t)).j;
ok('lists include assignees',ls[0].cards.find(c=>c.id===card.id).assignees.length===2);
ok('unassign works',(await call('DELETE',`/cards/${card.id}/members/${Bo.id}`,Bo.t)).s===200);
ok('revoke invite (owner)',(await call('DELETE',`/boards/${board.id}/invite`,A.t)).s===200);
ok('revoked token dead',(await call('GET',`/boards/join/${inv.token}`,C.t)).s===404);
ok('existing member keeps access after revoke',(await call('GET',`/boards/${board.id}`,Bo.t)).s===200);
ok('owner deletes board',(await call('DELETE',`/boards/${board.id}`,A.t)).s===200);
ok('member loses board after delete',(await call('GET',`/boards/${board.id}`,Bo.t)).s===404);
console.log('stamp',stamp);
