const B='http://localhost:3001';
const stamp=Date.now();
const call=async(m,p,t,body)=>{const r=await fetch(B+p,{method:m,headers:{'content-type':'application/json',...(t?{authorization:'Bearer '+t}:{})},body:body?JSON.stringify(body):undefined});let j=null;try{j=await r.json()}catch{}return{s:r.status,j}};
const reg=async(n)=>{const r=await call('POST','/auth/register',null,{email:`smoke-${n}-${stamp}@sprintio.test`,password:'smoke-pass-1234',firstName:'Smoke',lastName:n});return{t:r.j.accessToken,id:r.j.user.sub}};
const ok=(name,cond,extra='')=>{console.log((cond?'PASS ':'FAIL ')+name+(cond?'':' '+extra));if(!cond)process.exitCode=1};
const A=await reg('wa'),Bo=await reg('wb');
const legacy=(await call('POST','/boards',A.t,{title:'No ws'})).j;
const wsList=(await call('GET','/workspaces',A.t)).j;
ok('board without workspace gets a default one',wsList.length===1&&legacy.workspaceId===wsList[0].id);
const sw=(await call('POST','/workspaces',A.t,{name:'  Software '})).j;
ok('create workspace trims name',sw.name==='Software'&&sw.ownerId===A.id);
ok('empty name rejected',(await call('POST','/workspaces',A.t,{name:' '})).s===400);
const b1=(await call('POST','/boards',A.t,{title:'API',workspaceId:sw.id}));
ok('owner creates board in own workspace',b1.s===201&&b1.j.workspaceId===sw.id);
ok('stranger cannot create board in foreign workspace',(await call('POST','/boards',Bo.t,{title:'x',workspaceId:sw.id})).s===404);
ok('stranger does not see the workspace',!(await call('GET','/workspaces',Bo.t)).j.some(w=>w.id===sw.id));
const inv=(await call('POST',`/boards/${b1.j.id}/invite`,A.t)).j;
await call('POST',`/boards/join/${inv.token}`,Bo.t);
ok('board member sees its workspace',(await call('GET','/workspaces',Bo.t)).j.some(w=>w.id===sw.id));
ok('...but still cannot add boards to it',(await call('POST','/boards',Bo.t,{title:'x',workspaceId:sw.id})).s===404);
let bl=(await call('GET','/boards',Bo.t)).j.find(b=>b.id===b1.j.id);
ok('never-opened board has no lastViewedAt',bl.lastViewedAt===null&&bl.starred===false);
await call('GET',`/boards/${b1.j.id}`,Bo.t);
bl=(await call('GET','/boards',Bo.t)).j.find(b=>b.id===b1.j.id);
ok('opening a board stamps lastViewedAt',typeof bl.lastViewedAt==='string');
ok('...per user',(await call('GET','/boards',A.t)).j.find(b=>b.id===b1.j.id).lastViewedAt!==bl.lastViewedAt);
ok('boards list still never leaks token',(await call('GET','/boards',A.t)).j.every(x=>!('inviteToken' in x)&&!('members' in x)));
ok('member cannot rename workspace',(await call('PATCH',`/workspaces/${sw.id}`,Bo.t,{name:'x'})).s===404);
ok('member cannot delete workspace',(await call('DELETE',`/workspaces/${sw.id}`,Bo.t)).s===404);
const rn=await call('PATCH',`/workspaces/${sw.id}`,A.t,{name:'Engineering'});
ok('owner renames workspace',rn.s===200&&rn.j.name==='Engineering');
ok('rename rejects empty name',(await call('PATCH',`/workspaces/${sw.id}`,A.t,{name:''})).s===400);
ok('owner deletes workspace',(await call('DELETE',`/workspaces/${sw.id}`,A.t)).s===200);
ok('...and its boards go with it',(await call('GET',`/boards/${b1.j.id}`,A.t)).s===404);
ok('...other workspaces survive',(await call('GET',`/boards/${legacy.id}`,A.t)).s===200);
// ---- workspace invites ----
const C=await reg('wc'),D=await reg('wd');
const dept=(await call('POST','/workspaces',A.t,{name:'Admin dept'})).j;
const d1=(await call('POST','/boards',A.t,{title:'Invoices',workspaceId:dept.id})).j;
ok('stranger cannot mint workspace invite',(await call('POST',`/workspaces/${dept.id}/invite`,C.t)).s===404);
const wi=(await call('POST',`/workspaces/${dept.id}/invite`,A.t)).j;
ok('owner gets workspace invite token',typeof wi.token==='string'&&wi.token.length===48);
ok('owner sees token in list',(await call('GET','/workspaces',A.t)).j.find(w=>w.id===dept.id).inviteToken===wi.token);
const wpv=await call('GET',`/workspaces/join/${wi.token}`,C.t);
ok('workspace preview',wpv.s===200&&wpv.j.name==='Admin dept'&&wpv.j.isMember===false);
ok('stranger cannot read board before joining',(await call('GET',`/boards/${d1.id}`,C.t)).s===404);
ok('join workspace',(await call('POST',`/workspaces/join/${wi.token}`,C.t)).s===201);
ok('join workspace is idempotent',(await call('POST',`/workspaces/join/${wi.token}`,C.t)).s===201);
ok('joiner reads existing board',(await call('GET',`/boards/${d1.id}`,C.t)).s===200);
const cw=(await call('GET','/workspaces',C.t)).j.find(w=>w.id===dept.id);
ok('joiner is a member, never sees the token',cw.isMember===true&&cw.inviteToken===null);
const d2=await call('POST','/boards',C.t,{title:'Payroll',workspaceId:dept.id});
ok('workspace member creates a board in it',d2.s===201);
ok('...and the owner is on it',(await call('GET',`/boards/${d2.j.id}`,A.t)).s===200);
const d3=(await call('POST','/boards',A.t,{title:'Taxes',workspaceId:dept.id})).j;
ok('boards created later include existing members',(await call('GET',`/boards/${d3.id}`,C.t)).s===200);
const list3=(await call('POST',`/boards/${d3.id}/lists`,A.t,{title:'L'})).j;
const card3=(await call('POST',`/lists/${list3.id}/cards`,A.t,{title:'C'})).j;
ok('workspace member can be assigned',(await call('PUT',`/cards/${card3.id}/members/${C.id}`,A.t)).s===200);
const mem=(await call('GET',`/workspaces/${dept.id}/members`,C.t)).j;
ok('members list has owner + joiner',mem.length===2&&mem.some(m=>m.userId===A.id)&&mem.some(m=>m.userId===C.id));
ok('outsider cannot list members',(await call('GET',`/workspaces/${dept.id}/members`,D.t)).s===404);
ok('member cannot mint invite',(await call('POST',`/workspaces/${dept.id}/invite`,C.t)).s===404);
ok('member cannot remove others',(await call('DELETE',`/workspaces/${dept.id}/members/${A.id}`,C.t)).s===400);
await call('POST',`/workspaces/join/${wi.token}`,D.t);
ok('member cannot remove another member',(await call('DELETE',`/workspaces/${dept.id}/members/${D.id}`,C.t)).s===403);
ok('owner cannot leave',(await call('DELETE',`/workspaces/${dept.id}/members/${A.id}`,A.t)).s===400);
ok('member leaves',(await call('DELETE',`/workspaces/${dept.id}/members/${C.id}`,C.t)).s===200);
ok('...loses boards they did not create',(await call('GET',`/boards/${d1.id}`,C.t)).s===404);
ok('...keeps the board they created',(await call('GET',`/boards/${d2.j.id}`,C.t)).s===200);
ok('...and their assignments there are gone',(await call('GET',`/boards/${d3.id}/lists`,A.t)).j[0].cards[0].assignees.length===0);
ok('owner removes a member',(await call('DELETE',`/workspaces/${dept.id}/members/${D.id}`,A.t)).s===200&&(await call('GET',`/boards/${d1.id}`,D.t)).s===404);
ok('revoke workspace invite',(await call('DELETE',`/workspaces/${dept.id}/invite`,A.t)).s===200);
ok('revoked token is dead',(await call('GET',`/workspaces/join/${wi.token}`,D.t)).s===404);
